// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global.proto

package adapter.server.proto;

public final class Global {
  private Global() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GlobalCommandMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GlobalCommandMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .Header header = 1;</code>
     */
    adapter.server.proto.Common.Header getHeader();
    /**
     * <code>required .Header header = 1;</code>
     */
    adapter.server.proto.Common.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional bool ping = 2;</code>
     *
     * <pre>
     * a client (external) sanity check for testing
     * </pre>
     */
    boolean hasPing();
    /**
     * <code>optional bool ping = 2;</code>
     *
     * <pre>
     * a client (external) sanity check for testing
     * </pre>
     */
    boolean getPing();

    /**
     * <code>optional string message = 3;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional .Failure err = 4;</code>
     */
    boolean hasErr();
    /**
     * <code>optional .Failure err = 4;</code>
     */
    adapter.server.proto.Common.Failure getErr();
    /**
     * <code>optional .Failure err = 4;</code>
     */
    adapter.server.proto.Common.FailureOrBuilder getErrOrBuilder();

    /**
     * <code>optional .Query query = 5;</code>
     */
    boolean hasQuery();
    /**
     * <code>optional .Query query = 5;</code>
     */
    adapter.server.proto.Storage.Query getQuery();
    /**
     * <code>optional .Query query = 5;</code>
     */
    adapter.server.proto.Storage.QueryOrBuilder getQueryOrBuilder();

    /**
     * <code>optional .Response response = 6;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .Response response = 6;</code>
     */
    adapter.server.proto.Storage.Response getResponse();
    /**
     * <code>optional .Response response = 6;</code>
     */
    adapter.server.proto.Storage.ResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code GlobalCommandMessage}
   */
  public static final class GlobalCommandMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GlobalCommandMessage)
      GlobalCommandMessageOrBuilder {
    // Use GlobalCommandMessage.newBuilder() to construct.
    private GlobalCommandMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GlobalCommandMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GlobalCommandMessage defaultInstance;
    public static GlobalCommandMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GlobalCommandMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalCommandMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              adapter.server.proto.Common.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(adapter.server.proto.Common.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              payloadCase_ = 2;
              payload_ = input.readBool();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              payloadCase_ = 3;
              payload_ = bs;
              break;
            }
            case 34: {
              adapter.server.proto.Common.Failure.Builder subBuilder = null;
              if (payloadCase_ == 4) {
                subBuilder = ((adapter.server.proto.Common.Failure) payload_).toBuilder();
              }
              payload_ = input.readMessage(adapter.server.proto.Common.Failure.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((adapter.server.proto.Common.Failure) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 4;
              break;
            }
            case 42: {
              adapter.server.proto.Storage.Query.Builder subBuilder = null;
              if (payloadCase_ == 5) {
                subBuilder = ((adapter.server.proto.Storage.Query) payload_).toBuilder();
              }
              payload_ = input.readMessage(adapter.server.proto.Storage.Query.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((adapter.server.proto.Storage.Query) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 5;
              break;
            }
            case 50: {
              adapter.server.proto.Storage.Response.Builder subBuilder = null;
              if (payloadCase_ == 6) {
                subBuilder = ((adapter.server.proto.Storage.Response) payload_).toBuilder();
              }
              payload_ = input.readMessage(adapter.server.proto.Storage.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((adapter.server.proto.Storage.Response) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 6;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return adapter.server.proto.Global.internal_static_GlobalCommandMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return adapter.server.proto.Global.internal_static_GlobalCommandMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              adapter.server.proto.Global.GlobalCommandMessage.class, adapter.server.proto.Global.GlobalCommandMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GlobalCommandMessage> PARSER =
        new com.google.protobuf.AbstractParser<GlobalCommandMessage>() {
      public GlobalCommandMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalCommandMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalCommandMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      PING(2),
      MESSAGE(3),
      ERR(4),
      QUERY(5),
      RESPONSE(6),
      PAYLOAD_NOT_SET(0);
      private int value = 0;
      private PayloadCase(int value) {
        this.value = value;
      }
      public static PayloadCase valueOf(int value) {
        switch (value) {
          case 2: return PING;
          case 3: return MESSAGE;
          case 4: return ERR;
          case 5: return QUERY;
          case 6: return RESPONSE;
          case 0: return PAYLOAD_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.valueOf(
          payloadCase_);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private adapter.server.proto.Common.Header header_;
    /**
     * <code>required .Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Header header = 1;</code>
     */
    public adapter.server.proto.Common.Header getHeader() {
      return header_;
    }
    /**
     * <code>required .Header header = 1;</code>
     */
    public adapter.server.proto.Common.HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    public static final int PING_FIELD_NUMBER = 2;
    /**
     * <code>optional bool ping = 2;</code>
     *
     * <pre>
     * a client (external) sanity check for testing
     * </pre>
     */
    public boolean hasPing() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional bool ping = 2;</code>
     *
     * <pre>
     * a client (external) sanity check for testing
     * </pre>
     */
    public boolean getPing() {
      if (payloadCase_ == 2) {
        return (java.lang.Boolean) payload_;
      }
      return false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    /**
     * <code>optional string message = 3;</code>
     */
    public boolean hasMessage() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = "";
      if (payloadCase_ == 3) {
        ref = payload_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (payloadCase_ == 3)) {
          payload_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = "";
      if (payloadCase_ == 3) {
        ref = payload_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (payloadCase_ == 3) {
          payload_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERR_FIELD_NUMBER = 4;
    /**
     * <code>optional .Failure err = 4;</code>
     */
    public boolean hasErr() {
      return payloadCase_ == 4;
    }
    /**
     * <code>optional .Failure err = 4;</code>
     */
    public adapter.server.proto.Common.Failure getErr() {
      if (payloadCase_ == 4) {
         return (adapter.server.proto.Common.Failure) payload_;
      }
      return adapter.server.proto.Common.Failure.getDefaultInstance();
    }
    /**
     * <code>optional .Failure err = 4;</code>
     */
    public adapter.server.proto.Common.FailureOrBuilder getErrOrBuilder() {
      if (payloadCase_ == 4) {
         return (adapter.server.proto.Common.Failure) payload_;
      }
      return adapter.server.proto.Common.Failure.getDefaultInstance();
    }

    public static final int QUERY_FIELD_NUMBER = 5;
    /**
     * <code>optional .Query query = 5;</code>
     */
    public boolean hasQuery() {
      return payloadCase_ == 5;
    }
    /**
     * <code>optional .Query query = 5;</code>
     */
    public adapter.server.proto.Storage.Query getQuery() {
      if (payloadCase_ == 5) {
         return (adapter.server.proto.Storage.Query) payload_;
      }
      return adapter.server.proto.Storage.Query.getDefaultInstance();
    }
    /**
     * <code>optional .Query query = 5;</code>
     */
    public adapter.server.proto.Storage.QueryOrBuilder getQueryOrBuilder() {
      if (payloadCase_ == 5) {
         return (adapter.server.proto.Storage.Query) payload_;
      }
      return adapter.server.proto.Storage.Query.getDefaultInstance();
    }

    public static final int RESPONSE_FIELD_NUMBER = 6;
    /**
     * <code>optional .Response response = 6;</code>
     */
    public boolean hasResponse() {
      return payloadCase_ == 6;
    }
    /**
     * <code>optional .Response response = 6;</code>
     */
    public adapter.server.proto.Storage.Response getResponse() {
      if (payloadCase_ == 6) {
         return (adapter.server.proto.Storage.Response) payload_;
      }
      return adapter.server.proto.Storage.Response.getDefaultInstance();
    }
    /**
     * <code>optional .Response response = 6;</code>
     */
    public adapter.server.proto.Storage.ResponseOrBuilder getResponseOrBuilder() {
      if (payloadCase_ == 6) {
         return (adapter.server.proto.Storage.Response) payload_;
      }
      return adapter.server.proto.Storage.Response.getDefaultInstance();
    }

    private void initFields() {
      header_ = adapter.server.proto.Common.Header.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasErr()) {
        if (!getErr().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasQuery()) {
        if (!getQuery().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (payloadCase_ == 2) {
        output.writeBool(
            2, (boolean)((java.lang.Boolean) payload_));
      }
      if (payloadCase_ == 3) {
        output.writeBytes(3, getMessageBytes());
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (adapter.server.proto.Common.Failure) payload_);
      }
      if (payloadCase_ == 5) {
        output.writeMessage(5, (adapter.server.proto.Storage.Query) payload_);
      }
      if (payloadCase_ == 6) {
        output.writeMessage(6, (adapter.server.proto.Storage.Response) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              2, (boolean)((java.lang.Boolean) payload_));
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (adapter.server.proto.Common.Failure) payload_);
      }
      if (payloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (adapter.server.proto.Storage.Query) payload_);
      }
      if (payloadCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (adapter.server.proto.Storage.Response) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static adapter.server.proto.Global.GlobalCommandMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static adapter.server.proto.Global.GlobalCommandMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(adapter.server.proto.Global.GlobalCommandMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GlobalCommandMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GlobalCommandMessage)
        adapter.server.proto.Global.GlobalCommandMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return adapter.server.proto.Global.internal_static_GlobalCommandMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return adapter.server.proto.Global.internal_static_GlobalCommandMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                adapter.server.proto.Global.GlobalCommandMessage.class, adapter.server.proto.Global.GlobalCommandMessage.Builder.class);
      }

      // Construct using adapter.server.proto.Global.GlobalCommandMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = adapter.server.proto.Common.Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return adapter.server.proto.Global.internal_static_GlobalCommandMessage_descriptor;
      }

      public adapter.server.proto.Global.GlobalCommandMessage getDefaultInstanceForType() {
        return adapter.server.proto.Global.GlobalCommandMessage.getDefaultInstance();
      }

      public adapter.server.proto.Global.GlobalCommandMessage build() {
        adapter.server.proto.Global.GlobalCommandMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public adapter.server.proto.Global.GlobalCommandMessage buildPartial() {
        adapter.server.proto.Global.GlobalCommandMessage result = new adapter.server.proto.Global.GlobalCommandMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (payloadCase_ == 2) {
          result.payload_ = payload_;
        }
        if (payloadCase_ == 3) {
          result.payload_ = payload_;
        }
        if (payloadCase_ == 4) {
          if (errBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = errBuilder_.build();
          }
        }
        if (payloadCase_ == 5) {
          if (queryBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = queryBuilder_.build();
          }
        }
        if (payloadCase_ == 6) {
          if (responseBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = responseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof adapter.server.proto.Global.GlobalCommandMessage) {
          return mergeFrom((adapter.server.proto.Global.GlobalCommandMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(adapter.server.proto.Global.GlobalCommandMessage other) {
        if (other == adapter.server.proto.Global.GlobalCommandMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        switch (other.getPayloadCase()) {
          case PING: {
            setPing(other.getPing());
            break;
          }
          case MESSAGE: {
            payloadCase_ = 3;
            payload_ = other.payload_;
            onChanged();
            break;
          }
          case ERR: {
            mergeErr(other.getErr());
            break;
          }
          case QUERY: {
            mergeQuery(other.getQuery());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        if (hasErr()) {
          if (!getErr().isInitialized()) {
            
            return false;
          }
        }
        if (hasQuery()) {
          if (!getQuery().isInitialized()) {
            
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        adapter.server.proto.Global.GlobalCommandMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (adapter.server.proto.Global.GlobalCommandMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.valueOf(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private adapter.server.proto.Common.Header header_ = adapter.server.proto.Common.Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          adapter.server.proto.Common.Header, adapter.server.proto.Common.Header.Builder, adapter.server.proto.Common.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public adapter.server.proto.Common.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder setHeader(adapter.server.proto.Common.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder setHeader(
          adapter.server.proto.Common.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder mergeHeader(adapter.server.proto.Common.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != adapter.server.proto.Common.Header.getDefaultInstance()) {
            header_ =
              adapter.server.proto.Common.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = adapter.server.proto.Common.Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public adapter.server.proto.Common.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public adapter.server.proto.Common.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          adapter.server.proto.Common.Header, adapter.server.proto.Common.Header.Builder, adapter.server.proto.Common.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              adapter.server.proto.Common.Header, adapter.server.proto.Common.Header.Builder, adapter.server.proto.Common.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      /**
       * <code>optional bool ping = 2;</code>
       *
       * <pre>
       * a client (external) sanity check for testing
       * </pre>
       */
      public boolean hasPing() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional bool ping = 2;</code>
       *
       * <pre>
       * a client (external) sanity check for testing
       * </pre>
       */
      public boolean getPing() {
        if (payloadCase_ == 2) {
          return (java.lang.Boolean) payload_;
        }
        return false;
      }
      /**
       * <code>optional bool ping = 2;</code>
       *
       * <pre>
       * a client (external) sanity check for testing
       * </pre>
       */
      public Builder setPing(boolean value) {
        payloadCase_ = 2;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool ping = 2;</code>
       *
       * <pre>
       * a client (external) sanity check for testing
       * </pre>
       */
      public Builder clearPing() {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional string message = 3;</code>
       */
      public boolean hasMessage() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = "";
        if (payloadCase_ == 3) {
          ref = payload_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (payloadCase_ == 3) {
            if (bs.isValidUtf8()) {
              payload_ = s;
            }
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = "";
        if (payloadCase_ == 3) {
          ref = payload_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (payloadCase_ == 3) {
            payload_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  payloadCase_ = 3;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  payloadCase_ = 3;
        payload_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          adapter.server.proto.Common.Failure, adapter.server.proto.Common.Failure.Builder, adapter.server.proto.Common.FailureOrBuilder> errBuilder_;
      /**
       * <code>optional .Failure err = 4;</code>
       */
      public boolean hasErr() {
        return payloadCase_ == 4;
      }
      /**
       * <code>optional .Failure err = 4;</code>
       */
      public adapter.server.proto.Common.Failure getErr() {
        if (errBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (adapter.server.proto.Common.Failure) payload_;
          }
          return adapter.server.proto.Common.Failure.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return errBuilder_.getMessage();
          }
          return adapter.server.proto.Common.Failure.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Failure err = 4;</code>
       */
      public Builder setErr(adapter.server.proto.Common.Failure value) {
        if (errBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          errBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Failure err = 4;</code>
       */
      public Builder setErr(
          adapter.server.proto.Common.Failure.Builder builderForValue) {
        if (errBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          errBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Failure err = 4;</code>
       */
      public Builder mergeErr(adapter.server.proto.Common.Failure value) {
        if (errBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != adapter.server.proto.Common.Failure.getDefaultInstance()) {
            payload_ = adapter.server.proto.Common.Failure.newBuilder((adapter.server.proto.Common.Failure) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            errBuilder_.mergeFrom(value);
          }
          errBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Failure err = 4;</code>
       */
      public Builder clearErr() {
        if (errBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          errBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Failure err = 4;</code>
       */
      public adapter.server.proto.Common.Failure.Builder getErrBuilder() {
        return getErrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Failure err = 4;</code>
       */
      public adapter.server.proto.Common.FailureOrBuilder getErrOrBuilder() {
        if ((payloadCase_ == 4) && (errBuilder_ != null)) {
          return errBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (adapter.server.proto.Common.Failure) payload_;
          }
          return adapter.server.proto.Common.Failure.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Failure err = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          adapter.server.proto.Common.Failure, adapter.server.proto.Common.Failure.Builder, adapter.server.proto.Common.FailureOrBuilder> 
          getErrFieldBuilder() {
        if (errBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = adapter.server.proto.Common.Failure.getDefaultInstance();
          }
          errBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              adapter.server.proto.Common.Failure, adapter.server.proto.Common.Failure.Builder, adapter.server.proto.Common.FailureOrBuilder>(
                  (adapter.server.proto.Common.Failure) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        return errBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          adapter.server.proto.Storage.Query, adapter.server.proto.Storage.Query.Builder, adapter.server.proto.Storage.QueryOrBuilder> queryBuilder_;
      /**
       * <code>optional .Query query = 5;</code>
       */
      public boolean hasQuery() {
        return payloadCase_ == 5;
      }
      /**
       * <code>optional .Query query = 5;</code>
       */
      public adapter.server.proto.Storage.Query getQuery() {
        if (queryBuilder_ == null) {
          if (payloadCase_ == 5) {
            return (adapter.server.proto.Storage.Query) payload_;
          }
          return adapter.server.proto.Storage.Query.getDefaultInstance();
        } else {
          if (payloadCase_ == 5) {
            return queryBuilder_.getMessage();
          }
          return adapter.server.proto.Storage.Query.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Query query = 5;</code>
       */
      public Builder setQuery(adapter.server.proto.Storage.Query value) {
        if (queryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          queryBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Query query = 5;</code>
       */
      public Builder setQuery(
          adapter.server.proto.Storage.Query.Builder builderForValue) {
        if (queryBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          queryBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Query query = 5;</code>
       */
      public Builder mergeQuery(adapter.server.proto.Storage.Query value) {
        if (queryBuilder_ == null) {
          if (payloadCase_ == 5 &&
              payload_ != adapter.server.proto.Storage.Query.getDefaultInstance()) {
            payload_ = adapter.server.proto.Storage.Query.newBuilder((adapter.server.proto.Storage.Query) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 5) {
            queryBuilder_.mergeFrom(value);
          }
          queryBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Query query = 5;</code>
       */
      public Builder clearQuery() {
        if (queryBuilder_ == null) {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
          }
          queryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Query query = 5;</code>
       */
      public adapter.server.proto.Storage.Query.Builder getQueryBuilder() {
        return getQueryFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Query query = 5;</code>
       */
      public adapter.server.proto.Storage.QueryOrBuilder getQueryOrBuilder() {
        if ((payloadCase_ == 5) && (queryBuilder_ != null)) {
          return queryBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 5) {
            return (adapter.server.proto.Storage.Query) payload_;
          }
          return adapter.server.proto.Storage.Query.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Query query = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          adapter.server.proto.Storage.Query, adapter.server.proto.Storage.Query.Builder, adapter.server.proto.Storage.QueryOrBuilder> 
          getQueryFieldBuilder() {
        if (queryBuilder_ == null) {
          if (!(payloadCase_ == 5)) {
            payload_ = adapter.server.proto.Storage.Query.getDefaultInstance();
          }
          queryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              adapter.server.proto.Storage.Query, adapter.server.proto.Storage.Query.Builder, adapter.server.proto.Storage.QueryOrBuilder>(
                  (adapter.server.proto.Storage.Query) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 5;
        return queryBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          adapter.server.proto.Storage.Response, adapter.server.proto.Storage.Response.Builder, adapter.server.proto.Storage.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .Response response = 6;</code>
       */
      public boolean hasResponse() {
        return payloadCase_ == 6;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public adapter.server.proto.Storage.Response getResponse() {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 6) {
            return (adapter.server.proto.Storage.Response) payload_;
          }
          return adapter.server.proto.Storage.Response.getDefaultInstance();
        } else {
          if (payloadCase_ == 6) {
            return responseBuilder_.getMessage();
          }
          return adapter.server.proto.Storage.Response.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public Builder setResponse(adapter.server.proto.Storage.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public Builder setResponse(
          adapter.server.proto.Storage.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public Builder mergeResponse(adapter.server.proto.Storage.Response value) {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 6 &&
              payload_ != adapter.server.proto.Storage.Response.getDefaultInstance()) {
            payload_ = adapter.server.proto.Storage.Response.newBuilder((adapter.server.proto.Storage.Response) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 6) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public adapter.server.proto.Storage.Response.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public adapter.server.proto.Storage.ResponseOrBuilder getResponseOrBuilder() {
        if ((payloadCase_ == 6) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 6) {
            return (adapter.server.proto.Storage.Response) payload_;
          }
          return adapter.server.proto.Storage.Response.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          adapter.server.proto.Storage.Response, adapter.server.proto.Storage.Response.Builder, adapter.server.proto.Storage.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(payloadCase_ == 6)) {
            payload_ = adapter.server.proto.Storage.Response.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              adapter.server.proto.Storage.Response, adapter.server.proto.Storage.Response.Builder, adapter.server.proto.Storage.ResponseOrBuilder>(
                  (adapter.server.proto.Storage.Response) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 6;
        return responseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GlobalCommandMessage)
    }

    static {
      defaultInstance = new GlobalCommandMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GlobalCommandMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalCommandMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GlobalCommandMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014global.proto\032\014common.proto\032\rstorage.pr" +
      "oto\"\256\001\n\024GlobalCommandMessage\022\027\n\006header\030\001" +
      " \002(\0132\007.Header\022\016\n\004ping\030\002 \001(\010H\000\022\021\n\007message" +
      "\030\003 \001(\tH\000\022\027\n\003err\030\004 \001(\0132\010.FailureH\000\022\027\n\005que" +
      "ry\030\005 \001(\0132\006.QueryH\000\022\035\n\010response\030\006 \001(\0132\t.R" +
      "esponseH\000B\t\n\007payloadB\030\n\024adapter.server.p" +
      "rotoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          adapter.server.proto.Common.getDescriptor(),
          adapter.server.proto.Storage.getDescriptor(),
        }, assigner);
    internal_static_GlobalCommandMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GlobalCommandMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GlobalCommandMessage_descriptor,
        new java.lang.String[] { "Header", "Ping", "Message", "Err", "Query", "Response", "Payload", });
    adapter.server.proto.Common.getDescriptor();
    adapter.server.proto.Storage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
