// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeartBeatRPC.proto

package raft.proto;

public final class HeartBeatRPC {
  private HeartBeatRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required int32 leaderId = 2;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>required int32 leaderId = 2;</code>
     */
    int getLeaderId();

    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    boolean hasTimeStampOnLatestUpdate();
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    long getTimeStampOnLatestUpdate();
  }
  /**
   * Protobuf type {@code HeartBeat}
   */
  public static final class HeartBeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartBeat)
      HeartBeatOrBuilder {
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeat defaultInstance;
    public static HeartBeat getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              leaderId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStampOnLatestUpdate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.proto.HeartBeatRPC.internal_static_HeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.proto.HeartBeatRPC.internal_static_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.proto.HeartBeatRPC.HeartBeat.class, raft.proto.HeartBeatRPC.HeartBeat.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeat> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeat>() {
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int LEADERID_FIELD_NUMBER = 2;
    private int leaderId_;
    /**
     * <code>required int32 leaderId = 2;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 leaderId = 2;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int TIMESTAMPONLATESTUPDATE_FIELD_NUMBER = 3;
    private long timeStampOnLatestUpdate_;
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public boolean hasTimeStampOnLatestUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public long getTimeStampOnLatestUpdate() {
      return timeStampOnLatestUpdate_;
    }

    private void initFields() {
      term_ = 0;
      leaderId_ = 0;
      timeStampOnLatestUpdate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLeaderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStampOnLatestUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeStampOnLatestUpdate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeStampOnLatestUpdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static raft.proto.HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(raft.proto.HeartBeatRPC.HeartBeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeat)
        raft.proto.HeartBeatRPC.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raft.proto.HeartBeatRPC.HeartBeat.class, raft.proto.HeartBeatRPC.HeartBeat.Builder.class);
      }

      // Construct using raft.proto.HeartBeatRPC.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStampOnLatestUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeat_descriptor;
      }

      public raft.proto.HeartBeatRPC.HeartBeat getDefaultInstanceForType() {
        return raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance();
      }

      public raft.proto.HeartBeatRPC.HeartBeat build() {
        raft.proto.HeartBeatRPC.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public raft.proto.HeartBeatRPC.HeartBeat buildPartial() {
        raft.proto.HeartBeatRPC.HeartBeat result = new raft.proto.HeartBeatRPC.HeartBeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leaderId_ = leaderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStampOnLatestUpdate_ = timeStampOnLatestUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raft.proto.HeartBeatRPC.HeartBeat) {
          return mergeFrom((raft.proto.HeartBeatRPC.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raft.proto.HeartBeatRPC.HeartBeat other) {
        if (other == raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        if (other.hasTimeStampOnLatestUpdate()) {
          setTimeStampOnLatestUpdate(other.getTimeStampOnLatestUpdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          
          return false;
        }
        if (!hasLeaderId()) {
          
          return false;
        }
        if (!hasTimeStampOnLatestUpdate()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raft.proto.HeartBeatRPC.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raft.proto.HeartBeatRPC.HeartBeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private int leaderId_ ;
      /**
       * <code>required int32 leaderId = 2;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 leaderId = 2;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>required int32 leaderId = 2;</code>
       */
      public Builder setLeaderId(int value) {
        bitField0_ |= 0x00000002;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 leaderId = 2;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private long timeStampOnLatestUpdate_ ;
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public boolean hasTimeStampOnLatestUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public long getTimeStampOnLatestUpdate() {
        return timeStampOnLatestUpdate_;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder setTimeStampOnLatestUpdate(long value) {
        bitField0_ |= 0x00000004;
        timeStampOnLatestUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder clearTimeStampOnLatestUpdate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStampOnLatestUpdate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeat)
    }

    static {
      defaultInstance = new HeartBeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartBeat)
  }

  public interface HeartBeatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required int32 nodeId = 2;</code>
     */
    boolean hasNodeId();
    /**
     * <code>required int32 nodeId = 2;</code>
     */
    int getNodeId();

    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    boolean hasTimeStampOnLatestUpdate();
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    long getTimeStampOnLatestUpdate();
  }
  /**
   * Protobuf type {@code HeartBeatResponse}
   */
  public static final class HeartBeatResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartBeatResponse)
      HeartBeatResponseOrBuilder {
    // Use HeartBeatResponse.newBuilder() to construct.
    private HeartBeatResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeatResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeatResponse defaultInstance;
    public static HeartBeatResponse getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeatResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nodeId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStampOnLatestUpdate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.proto.HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.proto.HeartBeatRPC.internal_static_HeartBeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.proto.HeartBeatRPC.HeartBeatResponse.class, raft.proto.HeartBeatRPC.HeartBeatResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeatResponse> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeatResponse>() {
      public HeartBeatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatResponse> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code HeartBeatResponse.IsAlive}
     */
    public enum IsAlive
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>YES = 1;</code>
       */
      YES(0, 1),
      /**
       * <code>NO = 2;</code>
       */
      NO(1, 2),
      ;

      /**
       * <code>YES = 1;</code>
       */
      public static final int YES_VALUE = 1;
      /**
       * <code>NO = 2;</code>
       */
      public static final int NO_VALUE = 2;


      public final int getNumber() { return value; }

      public static IsAlive valueOf(int value) {
        switch (value) {
          case 1: return YES;
          case 2: return NO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IsAlive>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<IsAlive>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IsAlive>() {
              public IsAlive findValueByNumber(int number) {
                return IsAlive.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return raft.proto.HeartBeatRPC.HeartBeatResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final IsAlive[] VALUES = values();

      public static IsAlive valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private IsAlive(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:HeartBeatResponse.IsAlive)
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int NODEID_FIELD_NUMBER = 2;
    private int nodeId_;
    /**
     * <code>required int32 nodeId = 2;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 nodeId = 2;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }

    public static final int TIMESTAMPONLATESTUPDATE_FIELD_NUMBER = 3;
    private long timeStampOnLatestUpdate_;
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public boolean hasTimeStampOnLatestUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public long getTimeStampOnLatestUpdate() {
      return timeStampOnLatestUpdate_;
    }

    private void initFields() {
      term_ = 0;
      nodeId_ = 0;
      timeStampOnLatestUpdate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStampOnLatestUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, nodeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeStampOnLatestUpdate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, nodeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeStampOnLatestUpdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(raft.proto.HeartBeatRPC.HeartBeatResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatResponse)
        raft.proto.HeartBeatRPC.HeartBeatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raft.proto.HeartBeatRPC.HeartBeatResponse.class, raft.proto.HeartBeatRPC.HeartBeatResponse.Builder.class);
      }

      // Construct using raft.proto.HeartBeatRPC.HeartBeatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStampOnLatestUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
      }

      public raft.proto.HeartBeatRPC.HeartBeatResponse getDefaultInstanceForType() {
        return raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
      }

      public raft.proto.HeartBeatRPC.HeartBeatResponse build() {
        raft.proto.HeartBeatRPC.HeartBeatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public raft.proto.HeartBeatRPC.HeartBeatResponse buildPartial() {
        raft.proto.HeartBeatRPC.HeartBeatResponse result = new raft.proto.HeartBeatRPC.HeartBeatResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStampOnLatestUpdate_ = timeStampOnLatestUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raft.proto.HeartBeatRPC.HeartBeatResponse) {
          return mergeFrom((raft.proto.HeartBeatRPC.HeartBeatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raft.proto.HeartBeatRPC.HeartBeatResponse other) {
        if (other == raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasTimeStampOnLatestUpdate()) {
          setTimeStampOnLatestUpdate(other.getTimeStampOnLatestUpdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          
          return false;
        }
        if (!hasNodeId()) {
          
          return false;
        }
        if (!hasTimeStampOnLatestUpdate()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raft.proto.HeartBeatRPC.HeartBeatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raft.proto.HeartBeatRPC.HeartBeatResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private int nodeId_ ;
      /**
       * <code>required int32 nodeId = 2;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 nodeId = 2;</code>
       */
      public int getNodeId() {
        return nodeId_;
      }
      /**
       * <code>required int32 nodeId = 2;</code>
       */
      public Builder setNodeId(int value) {
        bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nodeId = 2;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeId_ = 0;
        onChanged();
        return this;
      }

      private long timeStampOnLatestUpdate_ ;
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public boolean hasTimeStampOnLatestUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public long getTimeStampOnLatestUpdate() {
        return timeStampOnLatestUpdate_;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder setTimeStampOnLatestUpdate(long value) {
        bitField0_ |= 0x00000004;
        timeStampOnLatestUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder clearTimeStampOnLatestUpdate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStampOnLatestUpdate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeatResponse)
    }

    static {
      defaultInstance = new HeartBeatResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartBeatResponse)
  }

  public interface HeartBeatPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    boolean hasUnixTimestamp();
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    long getUnixTimestamp();

    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    boolean hasHeartbeat();
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    raft.proto.HeartBeatRPC.HeartBeat getHeartbeat();
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    raft.proto.HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder();

    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    boolean hasHeartBeatResponse();
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    raft.proto.HeartBeatRPC.HeartBeatResponse getHeartBeatResponse();
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    raft.proto.HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder();
  }
  /**
   * Protobuf type {@code HeartBeatPacket}
   */
  public static final class HeartBeatPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartBeatPacket)
      HeartBeatPacketOrBuilder {
    // Use HeartBeatPacket.newBuilder() to construct.
    private HeartBeatPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeatPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeatPacket defaultInstance;
    public static HeartBeatPacket getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeatPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTimestamp_ = input.readInt64();
              break;
            }
            case 18: {
              raft.proto.HeartBeatRPC.HeartBeat.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((raft.proto.HeartBeatRPC.HeartBeat) payload_).toBuilder();
              }
              payload_ = input.readMessage(raft.proto.HeartBeatRPC.HeartBeat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((raft.proto.HeartBeatRPC.HeartBeat) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              raft.proto.HeartBeatRPC.HeartBeatResponse.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((raft.proto.HeartBeatRPC.HeartBeatResponse) payload_).toBuilder();
              }
              payload_ = input.readMessage(raft.proto.HeartBeatRPC.HeartBeatResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((raft.proto.HeartBeatRPC.HeartBeatResponse) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.proto.HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.proto.HeartBeatRPC.internal_static_HeartBeatPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.proto.HeartBeatRPC.HeartBeatPacket.class, raft.proto.HeartBeatRPC.HeartBeatPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeatPacket> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeatPacket>() {
      public HeartBeatPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      HEARTBEAT(2),
      HEARTBEATRESPONSE(3),
      PAYLOAD_NOT_SET(0);
      private int value = 0;
      private PayloadCase(int value) {
        this.value = value;
      }
      public static PayloadCase valueOf(int value) {
        switch (value) {
          case 2: return HEARTBEAT;
          case 3: return HEARTBEATRESPONSE;
          case 0: return PAYLOAD_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.valueOf(
          payloadCase_);
    }

    public static final int UNIXTIMESTAMP_FIELD_NUMBER = 1;
    private long unixTimestamp_;
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public boolean hasUnixTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public long getUnixTimestamp() {
      return unixTimestamp_;
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 2;
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public boolean hasHeartbeat() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public raft.proto.HeartBeatRPC.HeartBeat getHeartbeat() {
      if (payloadCase_ == 2) {
         return (raft.proto.HeartBeatRPC.HeartBeat) payload_;
      }
      return raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance();
    }
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public raft.proto.HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder() {
      if (payloadCase_ == 2) {
         return (raft.proto.HeartBeatRPC.HeartBeat) payload_;
      }
      return raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance();
    }

    public static final int HEARTBEATRESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public boolean hasHeartBeatResponse() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public raft.proto.HeartBeatRPC.HeartBeatResponse getHeartBeatResponse() {
      if (payloadCase_ == 3) {
         return (raft.proto.HeartBeatRPC.HeartBeatResponse) payload_;
      }
      return raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
    }
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public raft.proto.HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder() {
      if (payloadCase_ == 3) {
         return (raft.proto.HeartBeatRPC.HeartBeatResponse) payload_;
      }
      return raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
    }

    private void initFields() {
      unixTimestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnixTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHeartbeat()) {
        if (!getHeartbeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartBeatResponse()) {
        if (!getHeartBeatResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (raft.proto.HeartBeatRPC.HeartBeat) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (raft.proto.HeartBeatRPC.HeartBeatResponse) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (raft.proto.HeartBeatRPC.HeartBeat) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (raft.proto.HeartBeatRPC.HeartBeatResponse) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(raft.proto.HeartBeatRPC.HeartBeatPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatPacket)
        raft.proto.HeartBeatRPC.HeartBeatPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeatPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raft.proto.HeartBeatRPC.HeartBeatPacket.class, raft.proto.HeartBeatRPC.HeartBeatPacket.Builder.class);
      }

      // Construct using raft.proto.HeartBeatRPC.HeartBeatPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        unixTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raft.proto.HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
      }

      public raft.proto.HeartBeatRPC.HeartBeatPacket getDefaultInstanceForType() {
        return raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
      }

      public raft.proto.HeartBeatRPC.HeartBeatPacket build() {
        raft.proto.HeartBeatRPC.HeartBeatPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public raft.proto.HeartBeatRPC.HeartBeatPacket buildPartial() {
        raft.proto.HeartBeatRPC.HeartBeatPacket result = new raft.proto.HeartBeatRPC.HeartBeatPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTimestamp_ = unixTimestamp_;
        if (payloadCase_ == 2) {
          if (heartbeatBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = heartbeatBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (heartBeatResponseBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = heartBeatResponseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raft.proto.HeartBeatRPC.HeartBeatPacket) {
          return mergeFrom((raft.proto.HeartBeatRPC.HeartBeatPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raft.proto.HeartBeatRPC.HeartBeatPacket other) {
        if (other == raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance()) return this;
        if (other.hasUnixTimestamp()) {
          setUnixTimestamp(other.getUnixTimestamp());
        }
        switch (other.getPayloadCase()) {
          case HEARTBEAT: {
            mergeHeartbeat(other.getHeartbeat());
            break;
          }
          case HEARTBEATRESPONSE: {
            mergeHeartBeatResponse(other.getHeartBeatResponse());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnixTimestamp()) {
          
          return false;
        }
        if (hasHeartbeat()) {
          if (!getHeartbeat().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeartBeatResponse()) {
          if (!getHeartBeatResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raft.proto.HeartBeatRPC.HeartBeatPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raft.proto.HeartBeatRPC.HeartBeatPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.valueOf(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long unixTimestamp_ ;
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public boolean hasUnixTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public long getUnixTimestamp() {
        return unixTimestamp_;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder setUnixTimestamp(long value) {
        bitField0_ |= 0x00000001;
        unixTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder clearUnixTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.HeartBeatRPC.HeartBeat, raft.proto.HeartBeatRPC.HeartBeat.Builder, raft.proto.HeartBeatRPC.HeartBeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public boolean hasHeartbeat() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (raft.proto.HeartBeatRPC.HeartBeat) payload_;
          }
          return raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return heartbeatBuilder_.getMessage();
          }
          return raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder setHeartbeat(raft.proto.HeartBeatRPC.HeartBeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder setHeartbeat(
          raft.proto.HeartBeatRPC.HeartBeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder mergeHeartbeat(raft.proto.HeartBeatRPC.HeartBeat value) {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance()) {
            payload_ = raft.proto.HeartBeatRPC.HeartBeat.newBuilder((raft.proto.HeartBeatRPC.HeartBeat) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            heartbeatBuilder_.mergeFrom(value);
          }
          heartbeatBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartbeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeat.Builder getHeartbeatBuilder() {
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder() {
        if ((payloadCase_ == 2) && (heartbeatBuilder_ != null)) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (raft.proto.HeartBeatRPC.HeartBeat) payload_;
          }
          return raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.HeartBeatRPC.HeartBeat, raft.proto.HeartBeatRPC.HeartBeat.Builder, raft.proto.HeartBeatRPC.HeartBeatOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = raft.proto.HeartBeatRPC.HeartBeat.getDefaultInstance();
          }
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              raft.proto.HeartBeatRPC.HeartBeat, raft.proto.HeartBeatRPC.HeartBeat.Builder, raft.proto.HeartBeatRPC.HeartBeatOrBuilder>(
                  (raft.proto.HeartBeatRPC.HeartBeat) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        return heartbeatBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.HeartBeatRPC.HeartBeatResponse, raft.proto.HeartBeatRPC.HeartBeatResponse.Builder, raft.proto.HeartBeatRPC.HeartBeatResponseOrBuilder> heartBeatResponseBuilder_;
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public boolean hasHeartBeatResponse() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeatResponse getHeartBeatResponse() {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (raft.proto.HeartBeatRPC.HeartBeatResponse) payload_;
          }
          return raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return heartBeatResponseBuilder_.getMessage();
          }
          return raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder setHeartBeatResponse(raft.proto.HeartBeatRPC.HeartBeatResponse value) {
        if (heartBeatResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartBeatResponseBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder setHeartBeatResponse(
          raft.proto.HeartBeatRPC.HeartBeatResponse.Builder builderForValue) {
        if (heartBeatResponseBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartBeatResponseBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder mergeHeartBeatResponse(raft.proto.HeartBeatRPC.HeartBeatResponse value) {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance()) {
            payload_ = raft.proto.HeartBeatRPC.HeartBeatResponse.newBuilder((raft.proto.HeartBeatRPC.HeartBeatResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            heartBeatResponseBuilder_.mergeFrom(value);
          }
          heartBeatResponseBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder clearHeartBeatResponse() {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartBeatResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeatResponse.Builder getHeartBeatResponseBuilder() {
        return getHeartBeatResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder() {
        if ((payloadCase_ == 3) && (heartBeatResponseBuilder_ != null)) {
          return heartBeatResponseBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (raft.proto.HeartBeatRPC.HeartBeatResponse) payload_;
          }
          return raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.HeartBeatRPC.HeartBeatResponse, raft.proto.HeartBeatRPC.HeartBeatResponse.Builder, raft.proto.HeartBeatRPC.HeartBeatResponseOrBuilder> 
          getHeartBeatResponseFieldBuilder() {
        if (heartBeatResponseBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = raft.proto.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
          }
          heartBeatResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              raft.proto.HeartBeatRPC.HeartBeatResponse, raft.proto.HeartBeatRPC.HeartBeatResponse.Builder, raft.proto.HeartBeatRPC.HeartBeatResponseOrBuilder>(
                  (raft.proto.HeartBeatRPC.HeartBeatResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        return heartBeatResponseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeatPacket)
    }

    static {
      defaultInstance = new HeartBeatPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartBeatPacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartBeatResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartBeatPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HeartBeatRPC.proto\"L\n\tHeartBeat\022\014\n\004ter" +
      "m\030\001 \002(\005\022\020\n\010leaderId\030\002 \002(\005\022\037\n\027timeStampOn" +
      "LatestUpdate\030\003 \002(\003\"n\n\021HeartBeatResponse\022" +
      "\014\n\004term\030\001 \002(\005\022\016\n\006nodeId\030\002 \002(\005\022\037\n\027timeSta" +
      "mpOnLatestUpdate\030\003 \002(\003\"\032\n\007IsAlive\022\007\n\003YES" +
      "\020\001\022\006\n\002NO\020\002\"\205\001\n\017HeartBeatPacket\022\025\n\runixTi" +
      "mestamp\030\001 \002(\003\022\037\n\theartbeat\030\002 \001(\0132\n.Heart" +
      "BeatH\000\022/\n\021heartBeatResponse\030\003 \001(\0132\022.Hear" +
      "tBeatResponseH\000B\t\n\007payloadB\014\n\nraft.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartBeat_descriptor,
        new java.lang.String[] { "Term", "LeaderId", "TimeStampOnLatestUpdate", });
    internal_static_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartBeatResponse_descriptor,
        new java.lang.String[] { "Term", "NodeId", "TimeStampOnLatestUpdate", });
    internal_static_HeartBeatPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeartBeatPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartBeatPacket_descriptor,
        new java.lang.String[] { "UnixTimestamp", "Heartbeat", "HeartBeatResponse", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
