// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoteRPC.proto

package raft.proto;

public final class VoteRPC {
  private VoteRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestVoteRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestVoteRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required string candidateId = 2;</code>
     */
    boolean hasCandidateId();
    /**
     * <code>required string candidateId = 2;</code>
     */
    java.lang.String getCandidateId();
    /**
     * <code>required string candidateId = 2;</code>
     */
    com.google.protobuf.ByteString
        getCandidateIdBytes();

    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    boolean hasTimeStampOnLatestUpdate();
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    long getTimeStampOnLatestUpdate();
  }
  /**
   * Protobuf type {@code RequestVoteRPC}
   */
  public static final class RequestVoteRPC extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RequestVoteRPC)
      RequestVoteRPCOrBuilder {
    // Use RequestVoteRPC.newBuilder() to construct.
    private RequestVoteRPC(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestVoteRPC(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestVoteRPC defaultInstance;
    public static RequestVoteRPC getDefaultInstance() {
      return defaultInstance;
    }

    public RequestVoteRPC getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestVoteRPC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              candidateId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStampOnLatestUpdate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.proto.VoteRPC.internal_static_RequestVoteRPC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.proto.VoteRPC.internal_static_RequestVoteRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.proto.VoteRPC.RequestVoteRPC.class, raft.proto.VoteRPC.RequestVoteRPC.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestVoteRPC> PARSER =
        new com.google.protobuf.AbstractParser<RequestVoteRPC>() {
      public RequestVoteRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestVoteRPC(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestVoteRPC> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 2;
    private java.lang.Object candidateId_;
    /**
     * <code>required string candidateId = 2;</code>
     */
    public boolean hasCandidateId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string candidateId = 2;</code>
     */
    public java.lang.String getCandidateId() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          candidateId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string candidateId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateIdBytes() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMPONLATESTUPDATE_FIELD_NUMBER = 3;
    private long timeStampOnLatestUpdate_;
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public boolean hasTimeStampOnLatestUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public long getTimeStampOnLatestUpdate() {
      return timeStampOnLatestUpdate_;
    }

    private void initFields() {
      term_ = 0;
      candidateId_ = "";
      timeStampOnLatestUpdate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCandidateId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStampOnLatestUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCandidateIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeStampOnLatestUpdate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCandidateIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeStampOnLatestUpdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static raft.proto.VoteRPC.RequestVoteRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.VoteRPC.RequestVoteRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(raft.proto.VoteRPC.RequestVoteRPC prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestVoteRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestVoteRPC)
        raft.proto.VoteRPC.RequestVoteRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raft.proto.VoteRPC.internal_static_RequestVoteRPC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raft.proto.VoteRPC.internal_static_RequestVoteRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raft.proto.VoteRPC.RequestVoteRPC.class, raft.proto.VoteRPC.RequestVoteRPC.Builder.class);
      }

      // Construct using raft.proto.VoteRPC.RequestVoteRPC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStampOnLatestUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raft.proto.VoteRPC.internal_static_RequestVoteRPC_descriptor;
      }

      public raft.proto.VoteRPC.RequestVoteRPC getDefaultInstanceForType() {
        return raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance();
      }

      public raft.proto.VoteRPC.RequestVoteRPC build() {
        raft.proto.VoteRPC.RequestVoteRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public raft.proto.VoteRPC.RequestVoteRPC buildPartial() {
        raft.proto.VoteRPC.RequestVoteRPC result = new raft.proto.VoteRPC.RequestVoteRPC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateId_ = candidateId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStampOnLatestUpdate_ = timeStampOnLatestUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raft.proto.VoteRPC.RequestVoteRPC) {
          return mergeFrom((raft.proto.VoteRPC.RequestVoteRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raft.proto.VoteRPC.RequestVoteRPC other) {
        if (other == raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasCandidateId()) {
          bitField0_ |= 0x00000002;
          candidateId_ = other.candidateId_;
          onChanged();
        }
        if (other.hasTimeStampOnLatestUpdate()) {
          setTimeStampOnLatestUpdate(other.getTimeStampOnLatestUpdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          
          return false;
        }
        if (!hasCandidateId()) {
          
          return false;
        }
        if (!hasTimeStampOnLatestUpdate()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raft.proto.VoteRPC.RequestVoteRPC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raft.proto.VoteRPC.RequestVoteRPC) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object candidateId_ = "";
      /**
       * <code>required string candidateId = 2;</code>
       */
      public boolean hasCandidateId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public java.lang.String getCandidateId() {
        java.lang.Object ref = candidateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            candidateId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCandidateIdBytes() {
        java.lang.Object ref = candidateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          candidateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public Builder setCandidateId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public Builder clearCandidateId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateId_ = getDefaultInstance().getCandidateId();
        onChanged();
        return this;
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public Builder setCandidateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }

      private long timeStampOnLatestUpdate_ ;
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public boolean hasTimeStampOnLatestUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public long getTimeStampOnLatestUpdate() {
        return timeStampOnLatestUpdate_;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder setTimeStampOnLatestUpdate(long value) {
        bitField0_ |= 0x00000004;
        timeStampOnLatestUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder clearTimeStampOnLatestUpdate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStampOnLatestUpdate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RequestVoteRPC)
    }

    static {
      defaultInstance = new RequestVoteRPC(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RequestVoteRPC)
  }

  public interface ResponseVoteRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseVoteRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
     */
    boolean hasIsVoteGranted();
    /**
     * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
     */
    raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted getIsVoteGranted();
  }
  /**
   * Protobuf type {@code ResponseVoteRPC}
   */
  public static final class ResponseVoteRPC extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResponseVoteRPC)
      ResponseVoteRPCOrBuilder {
    // Use ResponseVoteRPC.newBuilder() to construct.
    private ResponseVoteRPC(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseVoteRPC(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseVoteRPC defaultInstance;
    public static ResponseVoteRPC getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseVoteRPC getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseVoteRPC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted value = raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                isVoteGranted_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.proto.VoteRPC.internal_static_ResponseVoteRPC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.proto.VoteRPC.internal_static_ResponseVoteRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.proto.VoteRPC.ResponseVoteRPC.class, raft.proto.VoteRPC.ResponseVoteRPC.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseVoteRPC> PARSER =
        new com.google.protobuf.AbstractParser<ResponseVoteRPC>() {
      public ResponseVoteRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseVoteRPC(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseVoteRPC> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ResponseVoteRPC.IsVoteGranted}
     */
    public enum IsVoteGranted
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>YES = 0;</code>
       */
      YES(0, 0),
      /**
       * <code>NO = 1;</code>
       */
      NO(1, 1),
      ;

      /**
       * <code>YES = 0;</code>
       */
      public static final int YES_VALUE = 0;
      /**
       * <code>NO = 1;</code>
       */
      public static final int NO_VALUE = 1;


      public final int getNumber() { return value; }

      public static IsVoteGranted valueOf(int value) {
        switch (value) {
          case 0: return YES;
          case 1: return NO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IsVoteGranted>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<IsVoteGranted>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IsVoteGranted>() {
              public IsVoteGranted findValueByNumber(int number) {
                return IsVoteGranted.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return raft.proto.VoteRPC.ResponseVoteRPC.getDescriptor().getEnumTypes().get(0);
      }

      private static final IsVoteGranted[] VALUES = values();

      public static IsVoteGranted valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private IsVoteGranted(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ResponseVoteRPC.IsVoteGranted)
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int ISVOTEGRANTED_FIELD_NUMBER = 2;
    private raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted isVoteGranted_;
    /**
     * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
     */
    public boolean hasIsVoteGranted() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
     */
    public raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted getIsVoteGranted() {
      return isVoteGranted_;
    }

    private void initFields() {
      term_ = 0;
      isVoteGranted_ = raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted.YES;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsVoteGranted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, isVoteGranted_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, isVoteGranted_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static raft.proto.VoteRPC.ResponseVoteRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.VoteRPC.ResponseVoteRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(raft.proto.VoteRPC.ResponseVoteRPC prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseVoteRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseVoteRPC)
        raft.proto.VoteRPC.ResponseVoteRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raft.proto.VoteRPC.internal_static_ResponseVoteRPC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raft.proto.VoteRPC.internal_static_ResponseVoteRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raft.proto.VoteRPC.ResponseVoteRPC.class, raft.proto.VoteRPC.ResponseVoteRPC.Builder.class);
      }

      // Construct using raft.proto.VoteRPC.ResponseVoteRPC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isVoteGranted_ = raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted.YES;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raft.proto.VoteRPC.internal_static_ResponseVoteRPC_descriptor;
      }

      public raft.proto.VoteRPC.ResponseVoteRPC getDefaultInstanceForType() {
        return raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance();
      }

      public raft.proto.VoteRPC.ResponseVoteRPC build() {
        raft.proto.VoteRPC.ResponseVoteRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public raft.proto.VoteRPC.ResponseVoteRPC buildPartial() {
        raft.proto.VoteRPC.ResponseVoteRPC result = new raft.proto.VoteRPC.ResponseVoteRPC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isVoteGranted_ = isVoteGranted_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raft.proto.VoteRPC.ResponseVoteRPC) {
          return mergeFrom((raft.proto.VoteRPC.ResponseVoteRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raft.proto.VoteRPC.ResponseVoteRPC other) {
        if (other == raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasIsVoteGranted()) {
          setIsVoteGranted(other.getIsVoteGranted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          
          return false;
        }
        if (!hasIsVoteGranted()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raft.proto.VoteRPC.ResponseVoteRPC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raft.proto.VoteRPC.ResponseVoteRPC) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted isVoteGranted_ = raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted.YES;
      /**
       * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
       */
      public boolean hasIsVoteGranted() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
       */
      public raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted getIsVoteGranted() {
        return isVoteGranted_;
      }
      /**
       * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
       */
      public Builder setIsVoteGranted(raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        isVoteGranted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
       */
      public Builder clearIsVoteGranted() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isVoteGranted_ = raft.proto.VoteRPC.ResponseVoteRPC.IsVoteGranted.YES;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResponseVoteRPC)
    }

    static {
      defaultInstance = new ResponseVoteRPC(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResponseVoteRPC)
  }

  public interface VoteRPCPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoteRPCPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    boolean hasUnixTimestamp();
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    long getUnixTimestamp();

    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    boolean hasRequestVoteRPC();
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    raft.proto.VoteRPC.RequestVoteRPC getRequestVoteRPC();
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    raft.proto.VoteRPC.RequestVoteRPCOrBuilder getRequestVoteRPCOrBuilder();

    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    boolean hasResponseVoteRPC();
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    raft.proto.VoteRPC.ResponseVoteRPC getResponseVoteRPC();
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    raft.proto.VoteRPC.ResponseVoteRPCOrBuilder getResponseVoteRPCOrBuilder();
  }
  /**
   * Protobuf type {@code VoteRPCPacket}
   */
  public static final class VoteRPCPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VoteRPCPacket)
      VoteRPCPacketOrBuilder {
    // Use VoteRPCPacket.newBuilder() to construct.
    private VoteRPCPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VoteRPCPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VoteRPCPacket defaultInstance;
    public static VoteRPCPacket getDefaultInstance() {
      return defaultInstance;
    }

    public VoteRPCPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VoteRPCPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTimestamp_ = input.readInt64();
              break;
            }
            case 18: {
              raft.proto.VoteRPC.RequestVoteRPC.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((raft.proto.VoteRPC.RequestVoteRPC) payload_).toBuilder();
              }
              payload_ = input.readMessage(raft.proto.VoteRPC.RequestVoteRPC.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((raft.proto.VoteRPC.RequestVoteRPC) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              raft.proto.VoteRPC.ResponseVoteRPC.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((raft.proto.VoteRPC.ResponseVoteRPC) payload_).toBuilder();
              }
              payload_ = input.readMessage(raft.proto.VoteRPC.ResponseVoteRPC.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((raft.proto.VoteRPC.ResponseVoteRPC) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.proto.VoteRPC.internal_static_VoteRPCPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.proto.VoteRPC.internal_static_VoteRPCPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.proto.VoteRPC.VoteRPCPacket.class, raft.proto.VoteRPC.VoteRPCPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<VoteRPCPacket> PARSER =
        new com.google.protobuf.AbstractParser<VoteRPCPacket>() {
      public VoteRPCPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteRPCPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VoteRPCPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      REQUESTVOTERPC(2),
      RESPONSEVOTERPC(3),
      PAYLOAD_NOT_SET(0);
      private int value = 0;
      private PayloadCase(int value) {
        this.value = value;
      }
      public static PayloadCase valueOf(int value) {
        switch (value) {
          case 2: return REQUESTVOTERPC;
          case 3: return RESPONSEVOTERPC;
          case 0: return PAYLOAD_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.valueOf(
          payloadCase_);
    }

    public static final int UNIXTIMESTAMP_FIELD_NUMBER = 1;
    private long unixTimestamp_;
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public boolean hasUnixTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public long getUnixTimestamp() {
      return unixTimestamp_;
    }

    public static final int REQUESTVOTERPC_FIELD_NUMBER = 2;
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    public boolean hasRequestVoteRPC() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    public raft.proto.VoteRPC.RequestVoteRPC getRequestVoteRPC() {
      if (payloadCase_ == 2) {
         return (raft.proto.VoteRPC.RequestVoteRPC) payload_;
      }
      return raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance();
    }
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    public raft.proto.VoteRPC.RequestVoteRPCOrBuilder getRequestVoteRPCOrBuilder() {
      if (payloadCase_ == 2) {
         return (raft.proto.VoteRPC.RequestVoteRPC) payload_;
      }
      return raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance();
    }

    public static final int RESPONSEVOTERPC_FIELD_NUMBER = 3;
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    public boolean hasResponseVoteRPC() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    public raft.proto.VoteRPC.ResponseVoteRPC getResponseVoteRPC() {
      if (payloadCase_ == 3) {
         return (raft.proto.VoteRPC.ResponseVoteRPC) payload_;
      }
      return raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance();
    }
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    public raft.proto.VoteRPC.ResponseVoteRPCOrBuilder getResponseVoteRPCOrBuilder() {
      if (payloadCase_ == 3) {
         return (raft.proto.VoteRPC.ResponseVoteRPC) payload_;
      }
      return raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance();
    }

    private void initFields() {
      unixTimestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnixTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequestVoteRPC()) {
        if (!getRequestVoteRPC().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponseVoteRPC()) {
        if (!getResponseVoteRPC().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (raft.proto.VoteRPC.RequestVoteRPC) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (raft.proto.VoteRPC.ResponseVoteRPC) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (raft.proto.VoteRPC.RequestVoteRPC) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (raft.proto.VoteRPC.ResponseVoteRPC) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static raft.proto.VoteRPC.VoteRPCPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.VoteRPC.VoteRPCPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(raft.proto.VoteRPC.VoteRPCPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VoteRPCPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VoteRPCPacket)
        raft.proto.VoteRPC.VoteRPCPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raft.proto.VoteRPC.internal_static_VoteRPCPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raft.proto.VoteRPC.internal_static_VoteRPCPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raft.proto.VoteRPC.VoteRPCPacket.class, raft.proto.VoteRPC.VoteRPCPacket.Builder.class);
      }

      // Construct using raft.proto.VoteRPC.VoteRPCPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        unixTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raft.proto.VoteRPC.internal_static_VoteRPCPacket_descriptor;
      }

      public raft.proto.VoteRPC.VoteRPCPacket getDefaultInstanceForType() {
        return raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance();
      }

      public raft.proto.VoteRPC.VoteRPCPacket build() {
        raft.proto.VoteRPC.VoteRPCPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public raft.proto.VoteRPC.VoteRPCPacket buildPartial() {
        raft.proto.VoteRPC.VoteRPCPacket result = new raft.proto.VoteRPC.VoteRPCPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTimestamp_ = unixTimestamp_;
        if (payloadCase_ == 2) {
          if (requestVoteRPCBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = requestVoteRPCBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (responseVoteRPCBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = responseVoteRPCBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raft.proto.VoteRPC.VoteRPCPacket) {
          return mergeFrom((raft.proto.VoteRPC.VoteRPCPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raft.proto.VoteRPC.VoteRPCPacket other) {
        if (other == raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance()) return this;
        if (other.hasUnixTimestamp()) {
          setUnixTimestamp(other.getUnixTimestamp());
        }
        switch (other.getPayloadCase()) {
          case REQUESTVOTERPC: {
            mergeRequestVoteRPC(other.getRequestVoteRPC());
            break;
          }
          case RESPONSEVOTERPC: {
            mergeResponseVoteRPC(other.getResponseVoteRPC());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnixTimestamp()) {
          
          return false;
        }
        if (hasRequestVoteRPC()) {
          if (!getRequestVoteRPC().isInitialized()) {
            
            return false;
          }
        }
        if (hasResponseVoteRPC()) {
          if (!getResponseVoteRPC().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raft.proto.VoteRPC.VoteRPCPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raft.proto.VoteRPC.VoteRPCPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.valueOf(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long unixTimestamp_ ;
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public boolean hasUnixTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public long getUnixTimestamp() {
        return unixTimestamp_;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder setUnixTimestamp(long value) {
        bitField0_ |= 0x00000001;
        unixTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder clearUnixTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.VoteRPC.RequestVoteRPC, raft.proto.VoteRPC.RequestVoteRPC.Builder, raft.proto.VoteRPC.RequestVoteRPCOrBuilder> requestVoteRPCBuilder_;
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public boolean hasRequestVoteRPC() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public raft.proto.VoteRPC.RequestVoteRPC getRequestVoteRPC() {
        if (requestVoteRPCBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (raft.proto.VoteRPC.RequestVoteRPC) payload_;
          }
          return raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return requestVoteRPCBuilder_.getMessage();
          }
          return raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance();
        }
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public Builder setRequestVoteRPC(raft.proto.VoteRPC.RequestVoteRPC value) {
        if (requestVoteRPCBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          requestVoteRPCBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public Builder setRequestVoteRPC(
          raft.proto.VoteRPC.RequestVoteRPC.Builder builderForValue) {
        if (requestVoteRPCBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          requestVoteRPCBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public Builder mergeRequestVoteRPC(raft.proto.VoteRPC.RequestVoteRPC value) {
        if (requestVoteRPCBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance()) {
            payload_ = raft.proto.VoteRPC.RequestVoteRPC.newBuilder((raft.proto.VoteRPC.RequestVoteRPC) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            requestVoteRPCBuilder_.mergeFrom(value);
          }
          requestVoteRPCBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public Builder clearRequestVoteRPC() {
        if (requestVoteRPCBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          requestVoteRPCBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public raft.proto.VoteRPC.RequestVoteRPC.Builder getRequestVoteRPCBuilder() {
        return getRequestVoteRPCFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public raft.proto.VoteRPC.RequestVoteRPCOrBuilder getRequestVoteRPCOrBuilder() {
        if ((payloadCase_ == 2) && (requestVoteRPCBuilder_ != null)) {
          return requestVoteRPCBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (raft.proto.VoteRPC.RequestVoteRPC) payload_;
          }
          return raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance();
        }
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.VoteRPC.RequestVoteRPC, raft.proto.VoteRPC.RequestVoteRPC.Builder, raft.proto.VoteRPC.RequestVoteRPCOrBuilder> 
          getRequestVoteRPCFieldBuilder() {
        if (requestVoteRPCBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = raft.proto.VoteRPC.RequestVoteRPC.getDefaultInstance();
          }
          requestVoteRPCBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              raft.proto.VoteRPC.RequestVoteRPC, raft.proto.VoteRPC.RequestVoteRPC.Builder, raft.proto.VoteRPC.RequestVoteRPCOrBuilder>(
                  (raft.proto.VoteRPC.RequestVoteRPC) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        return requestVoteRPCBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.VoteRPC.ResponseVoteRPC, raft.proto.VoteRPC.ResponseVoteRPC.Builder, raft.proto.VoteRPC.ResponseVoteRPCOrBuilder> responseVoteRPCBuilder_;
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public boolean hasResponseVoteRPC() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public raft.proto.VoteRPC.ResponseVoteRPC getResponseVoteRPC() {
        if (responseVoteRPCBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (raft.proto.VoteRPC.ResponseVoteRPC) payload_;
          }
          return raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return responseVoteRPCBuilder_.getMessage();
          }
          return raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance();
        }
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public Builder setResponseVoteRPC(raft.proto.VoteRPC.ResponseVoteRPC value) {
        if (responseVoteRPCBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          responseVoteRPCBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public Builder setResponseVoteRPC(
          raft.proto.VoteRPC.ResponseVoteRPC.Builder builderForValue) {
        if (responseVoteRPCBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          responseVoteRPCBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public Builder mergeResponseVoteRPC(raft.proto.VoteRPC.ResponseVoteRPC value) {
        if (responseVoteRPCBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance()) {
            payload_ = raft.proto.VoteRPC.ResponseVoteRPC.newBuilder((raft.proto.VoteRPC.ResponseVoteRPC) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            responseVoteRPCBuilder_.mergeFrom(value);
          }
          responseVoteRPCBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public Builder clearResponseVoteRPC() {
        if (responseVoteRPCBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          responseVoteRPCBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public raft.proto.VoteRPC.ResponseVoteRPC.Builder getResponseVoteRPCBuilder() {
        return getResponseVoteRPCFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public raft.proto.VoteRPC.ResponseVoteRPCOrBuilder getResponseVoteRPCOrBuilder() {
        if ((payloadCase_ == 3) && (responseVoteRPCBuilder_ != null)) {
          return responseVoteRPCBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (raft.proto.VoteRPC.ResponseVoteRPC) payload_;
          }
          return raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance();
        }
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.VoteRPC.ResponseVoteRPC, raft.proto.VoteRPC.ResponseVoteRPC.Builder, raft.proto.VoteRPC.ResponseVoteRPCOrBuilder> 
          getResponseVoteRPCFieldBuilder() {
        if (responseVoteRPCBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = raft.proto.VoteRPC.ResponseVoteRPC.getDefaultInstance();
          }
          responseVoteRPCBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              raft.proto.VoteRPC.ResponseVoteRPC, raft.proto.VoteRPC.ResponseVoteRPC.Builder, raft.proto.VoteRPC.ResponseVoteRPCOrBuilder>(
                  (raft.proto.VoteRPC.ResponseVoteRPC) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        return responseVoteRPCBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:VoteRPCPacket)
    }

    static {
      defaultInstance = new VoteRPCPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VoteRPCPacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestVoteRPC_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestVoteRPC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseVoteRPC_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResponseVoteRPC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteRPCPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VoteRPCPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rVoteRPC.proto\"T\n\016RequestVoteRPC\022\014\n\004ter" +
      "m\030\001 \002(\005\022\023\n\013candidateId\030\002 \002(\t\022\037\n\027timeStam" +
      "pOnLatestUpdate\030\003 \002(\003\"x\n\017ResponseVoteRPC" +
      "\022\014\n\004term\030\001 \002(\005\0225\n\risVoteGranted\030\002 \002(\0162\036." +
      "ResponseVoteRPC.IsVoteGranted\" \n\rIsVoteG" +
      "ranted\022\007\n\003YES\020\000\022\006\n\002NO\020\001\"\211\001\n\rVoteRPCPacke" +
      "t\022\025\n\runixTimestamp\030\001 \002(\003\022)\n\016requestVoteR" +
      "PC\030\002 \001(\0132\017.RequestVoteRPCH\000\022+\n\017responseV" +
      "oteRPC\030\003 \001(\0132\020.ResponseVoteRPCH\000B\t\n\007payl" +
      "oadB\014\n\nraft.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestVoteRPC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestVoteRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RequestVoteRPC_descriptor,
        new java.lang.String[] { "Term", "CandidateId", "TimeStampOnLatestUpdate", });
    internal_static_ResponseVoteRPC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseVoteRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResponseVoteRPC_descriptor,
        new java.lang.String[] { "Term", "IsVoteGranted", });
    internal_static_VoteRPCPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VoteRPCPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VoteRPCPacket_descriptor,
        new java.lang.String[] { "UnixTimestamp", "RequestVoteRPC", "ResponseVoteRPC", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
