// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Work.proto

package raft.proto;

public final class Work {
  private Work() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WorkMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WorkMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    boolean hasUnixTimeStamp();
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    long getUnixTimeStamp();

    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    boolean hasAppendEntriesPacket();
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    raft.proto.AppendEntriesRPC.AppendEntriesPacket getAppendEntriesPacket();
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    raft.proto.AppendEntriesRPC.AppendEntriesPacketOrBuilder getAppendEntriesPacketOrBuilder();

    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    boolean hasHeartBeatPacket();
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    raft.proto.HeartBeatRPC.HeartBeatPacket getHeartBeatPacket();
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    raft.proto.HeartBeatRPC.HeartBeatPacketOrBuilder getHeartBeatPacketOrBuilder();

    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    boolean hasVoteRPCPacket();
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    raft.proto.VoteRPC.VoteRPCPacket getVoteRPCPacket();
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    raft.proto.VoteRPC.VoteRPCPacketOrBuilder getVoteRPCPacketOrBuilder();

    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    boolean hasTrivialPing();
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    raft.proto.Ping.PingMessage getTrivialPing();
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    raft.proto.Ping.PingMessageOrBuilder getTrivialPingOrBuilder();
  }
  /**
   * Protobuf type {@code WorkMessage}
   *
   * <pre>
   *-------------------------------------------------------------------------------------
   * </pre>
   */
  public static final class WorkMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:WorkMessage)
      WorkMessageOrBuilder {
    // Use WorkMessage.newBuilder() to construct.
    private WorkMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorkMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorkMessage defaultInstance;
    public static WorkMessage getDefaultInstance() {
      return defaultInstance;
    }

    public WorkMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorkMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTimeStamp_ = input.readInt64();
              break;
            }
            case 18: {
              raft.proto.AppendEntriesRPC.AppendEntriesPacket.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_).toBuilder();
              }
              payload_ = input.readMessage(raft.proto.AppendEntriesRPC.AppendEntriesPacket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              raft.proto.HeartBeatRPC.HeartBeatPacket.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((raft.proto.HeartBeatRPC.HeartBeatPacket) payload_).toBuilder();
              }
              payload_ = input.readMessage(raft.proto.HeartBeatRPC.HeartBeatPacket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((raft.proto.HeartBeatRPC.HeartBeatPacket) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
            case 34: {
              raft.proto.VoteRPC.VoteRPCPacket.Builder subBuilder = null;
              if (payloadCase_ == 4) {
                subBuilder = ((raft.proto.VoteRPC.VoteRPCPacket) payload_).toBuilder();
              }
              payload_ = input.readMessage(raft.proto.VoteRPC.VoteRPCPacket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((raft.proto.VoteRPC.VoteRPCPacket) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 4;
              break;
            }
            case 42: {
              raft.proto.Ping.PingMessage.Builder subBuilder = null;
              if (payloadCase_ == 5) {
                subBuilder = ((raft.proto.Ping.PingMessage) payload_).toBuilder();
              }
              payload_ = input.readMessage(raft.proto.Ping.PingMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((raft.proto.Ping.PingMessage) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 5;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raft.proto.Work.internal_static_WorkMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raft.proto.Work.internal_static_WorkMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raft.proto.Work.WorkMessage.class, raft.proto.Work.WorkMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<WorkMessage> PARSER =
        new com.google.protobuf.AbstractParser<WorkMessage>() {
      public WorkMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorkMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      APPENDENTRIESPACKET(2),
      HEARTBEATPACKET(3),
      VOTERPCPACKET(4),
      TRIVIALPING(5),
      PAYLOAD_NOT_SET(0);
      private int value = 0;
      private PayloadCase(int value) {
        this.value = value;
      }
      public static PayloadCase valueOf(int value) {
        switch (value) {
          case 2: return APPENDENTRIESPACKET;
          case 3: return HEARTBEATPACKET;
          case 4: return VOTERPCPACKET;
          case 5: return TRIVIALPING;
          case 0: return PAYLOAD_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.valueOf(
          payloadCase_);
    }

    public static final int UNIXTIMESTAMP_FIELD_NUMBER = 1;
    private long unixTimeStamp_;
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    public boolean hasUnixTimeStamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    public long getUnixTimeStamp() {
      return unixTimeStamp_;
    }

    public static final int APPENDENTRIESPACKET_FIELD_NUMBER = 2;
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    public boolean hasAppendEntriesPacket() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    public raft.proto.AppendEntriesRPC.AppendEntriesPacket getAppendEntriesPacket() {
      if (payloadCase_ == 2) {
         return (raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_;
      }
      return raft.proto.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
    }
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    public raft.proto.AppendEntriesRPC.AppendEntriesPacketOrBuilder getAppendEntriesPacketOrBuilder() {
      if (payloadCase_ == 2) {
         return (raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_;
      }
      return raft.proto.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
    }

    public static final int HEARTBEATPACKET_FIELD_NUMBER = 3;
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    public boolean hasHeartBeatPacket() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    public raft.proto.HeartBeatRPC.HeartBeatPacket getHeartBeatPacket() {
      if (payloadCase_ == 3) {
         return (raft.proto.HeartBeatRPC.HeartBeatPacket) payload_;
      }
      return raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
    }
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    public raft.proto.HeartBeatRPC.HeartBeatPacketOrBuilder getHeartBeatPacketOrBuilder() {
      if (payloadCase_ == 3) {
         return (raft.proto.HeartBeatRPC.HeartBeatPacket) payload_;
      }
      return raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
    }

    public static final int VOTERPCPACKET_FIELD_NUMBER = 4;
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    public boolean hasVoteRPCPacket() {
      return payloadCase_ == 4;
    }
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    public raft.proto.VoteRPC.VoteRPCPacket getVoteRPCPacket() {
      if (payloadCase_ == 4) {
         return (raft.proto.VoteRPC.VoteRPCPacket) payload_;
      }
      return raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance();
    }
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    public raft.proto.VoteRPC.VoteRPCPacketOrBuilder getVoteRPCPacketOrBuilder() {
      if (payloadCase_ == 4) {
         return (raft.proto.VoteRPC.VoteRPCPacket) payload_;
      }
      return raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance();
    }

    public static final int TRIVIALPING_FIELD_NUMBER = 5;
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    public boolean hasTrivialPing() {
      return payloadCase_ == 5;
    }
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    public raft.proto.Ping.PingMessage getTrivialPing() {
      if (payloadCase_ == 5) {
         return (raft.proto.Ping.PingMessage) payload_;
      }
      return raft.proto.Ping.PingMessage.getDefaultInstance();
    }
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    public raft.proto.Ping.PingMessageOrBuilder getTrivialPingOrBuilder() {
      if (payloadCase_ == 5) {
         return (raft.proto.Ping.PingMessage) payload_;
      }
      return raft.proto.Ping.PingMessage.getDefaultInstance();
    }

    private void initFields() {
      unixTimeStamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnixTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAppendEntriesPacket()) {
        if (!getAppendEntriesPacket().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartBeatPacket()) {
        if (!getHeartBeatPacket().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasVoteRPCPacket()) {
        if (!getVoteRPCPacket().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTrivialPing()) {
        if (!getTrivialPing().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, unixTimeStamp_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (raft.proto.HeartBeatRPC.HeartBeatPacket) payload_);
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (raft.proto.VoteRPC.VoteRPCPacket) payload_);
      }
      if (payloadCase_ == 5) {
        output.writeMessage(5, (raft.proto.Ping.PingMessage) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, unixTimeStamp_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (raft.proto.HeartBeatRPC.HeartBeatPacket) payload_);
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (raft.proto.VoteRPC.VoteRPCPacket) payload_);
      }
      if (payloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (raft.proto.Ping.PingMessage) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static raft.proto.Work.WorkMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.Work.WorkMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.Work.WorkMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raft.proto.Work.WorkMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raft.proto.Work.WorkMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.Work.WorkMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static raft.proto.Work.WorkMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static raft.proto.Work.WorkMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static raft.proto.Work.WorkMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static raft.proto.Work.WorkMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(raft.proto.Work.WorkMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WorkMessage}
     *
     * <pre>
     *-------------------------------------------------------------------------------------
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WorkMessage)
        raft.proto.Work.WorkMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raft.proto.Work.internal_static_WorkMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raft.proto.Work.internal_static_WorkMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raft.proto.Work.WorkMessage.class, raft.proto.Work.WorkMessage.Builder.class);
      }

      // Construct using raft.proto.Work.WorkMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        unixTimeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raft.proto.Work.internal_static_WorkMessage_descriptor;
      }

      public raft.proto.Work.WorkMessage getDefaultInstanceForType() {
        return raft.proto.Work.WorkMessage.getDefaultInstance();
      }

      public raft.proto.Work.WorkMessage build() {
        raft.proto.Work.WorkMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public raft.proto.Work.WorkMessage buildPartial() {
        raft.proto.Work.WorkMessage result = new raft.proto.Work.WorkMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTimeStamp_ = unixTimeStamp_;
        if (payloadCase_ == 2) {
          if (appendEntriesPacketBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = appendEntriesPacketBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (heartBeatPacketBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = heartBeatPacketBuilder_.build();
          }
        }
        if (payloadCase_ == 4) {
          if (voteRPCPacketBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = voteRPCPacketBuilder_.build();
          }
        }
        if (payloadCase_ == 5) {
          if (trivialPingBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = trivialPingBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raft.proto.Work.WorkMessage) {
          return mergeFrom((raft.proto.Work.WorkMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raft.proto.Work.WorkMessage other) {
        if (other == raft.proto.Work.WorkMessage.getDefaultInstance()) return this;
        if (other.hasUnixTimeStamp()) {
          setUnixTimeStamp(other.getUnixTimeStamp());
        }
        switch (other.getPayloadCase()) {
          case APPENDENTRIESPACKET: {
            mergeAppendEntriesPacket(other.getAppendEntriesPacket());
            break;
          }
          case HEARTBEATPACKET: {
            mergeHeartBeatPacket(other.getHeartBeatPacket());
            break;
          }
          case VOTERPCPACKET: {
            mergeVoteRPCPacket(other.getVoteRPCPacket());
            break;
          }
          case TRIVIALPING: {
            mergeTrivialPing(other.getTrivialPing());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnixTimeStamp()) {
          
          return false;
        }
        if (hasAppendEntriesPacket()) {
          if (!getAppendEntriesPacket().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeartBeatPacket()) {
          if (!getHeartBeatPacket().isInitialized()) {
            
            return false;
          }
        }
        if (hasVoteRPCPacket()) {
          if (!getVoteRPCPacket().isInitialized()) {
            
            return false;
          }
        }
        if (hasTrivialPing()) {
          if (!getTrivialPing().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raft.proto.Work.WorkMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raft.proto.Work.WorkMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.valueOf(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long unixTimeStamp_ ;
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public boolean hasUnixTimeStamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public long getUnixTimeStamp() {
        return unixTimeStamp_;
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public Builder setUnixTimeStamp(long value) {
        bitField0_ |= 0x00000001;
        unixTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public Builder clearUnixTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTimeStamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.AppendEntriesRPC.AppendEntriesPacket, raft.proto.AppendEntriesRPC.AppendEntriesPacket.Builder, raft.proto.AppendEntriesRPC.AppendEntriesPacketOrBuilder> appendEntriesPacketBuilder_;
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public boolean hasAppendEntriesPacket() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public raft.proto.AppendEntriesRPC.AppendEntriesPacket getAppendEntriesPacket() {
        if (appendEntriesPacketBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_;
          }
          return raft.proto.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return appendEntriesPacketBuilder_.getMessage();
          }
          return raft.proto.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public Builder setAppendEntriesPacket(raft.proto.AppendEntriesRPC.AppendEntriesPacket value) {
        if (appendEntriesPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          appendEntriesPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public Builder setAppendEntriesPacket(
          raft.proto.AppendEntriesRPC.AppendEntriesPacket.Builder builderForValue) {
        if (appendEntriesPacketBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          appendEntriesPacketBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public Builder mergeAppendEntriesPacket(raft.proto.AppendEntriesRPC.AppendEntriesPacket value) {
        if (appendEntriesPacketBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != raft.proto.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance()) {
            payload_ = raft.proto.AppendEntriesRPC.AppendEntriesPacket.newBuilder((raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            appendEntriesPacketBuilder_.mergeFrom(value);
          }
          appendEntriesPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public Builder clearAppendEntriesPacket() {
        if (appendEntriesPacketBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          appendEntriesPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public raft.proto.AppendEntriesRPC.AppendEntriesPacket.Builder getAppendEntriesPacketBuilder() {
        return getAppendEntriesPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public raft.proto.AppendEntriesRPC.AppendEntriesPacketOrBuilder getAppendEntriesPacketOrBuilder() {
        if ((payloadCase_ == 2) && (appendEntriesPacketBuilder_ != null)) {
          return appendEntriesPacketBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_;
          }
          return raft.proto.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.AppendEntriesRPC.AppendEntriesPacket, raft.proto.AppendEntriesRPC.AppendEntriesPacket.Builder, raft.proto.AppendEntriesRPC.AppendEntriesPacketOrBuilder> 
          getAppendEntriesPacketFieldBuilder() {
        if (appendEntriesPacketBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = raft.proto.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
          }
          appendEntriesPacketBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              raft.proto.AppendEntriesRPC.AppendEntriesPacket, raft.proto.AppendEntriesRPC.AppendEntriesPacket.Builder, raft.proto.AppendEntriesRPC.AppendEntriesPacketOrBuilder>(
                  (raft.proto.AppendEntriesRPC.AppendEntriesPacket) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        return appendEntriesPacketBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.HeartBeatRPC.HeartBeatPacket, raft.proto.HeartBeatRPC.HeartBeatPacket.Builder, raft.proto.HeartBeatRPC.HeartBeatPacketOrBuilder> heartBeatPacketBuilder_;
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public boolean hasHeartBeatPacket() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeatPacket getHeartBeatPacket() {
        if (heartBeatPacketBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (raft.proto.HeartBeatRPC.HeartBeatPacket) payload_;
          }
          return raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return heartBeatPacketBuilder_.getMessage();
          }
          return raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public Builder setHeartBeatPacket(raft.proto.HeartBeatRPC.HeartBeatPacket value) {
        if (heartBeatPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartBeatPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public Builder setHeartBeatPacket(
          raft.proto.HeartBeatRPC.HeartBeatPacket.Builder builderForValue) {
        if (heartBeatPacketBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartBeatPacketBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public Builder mergeHeartBeatPacket(raft.proto.HeartBeatRPC.HeartBeatPacket value) {
        if (heartBeatPacketBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance()) {
            payload_ = raft.proto.HeartBeatRPC.HeartBeatPacket.newBuilder((raft.proto.HeartBeatRPC.HeartBeatPacket) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            heartBeatPacketBuilder_.mergeFrom(value);
          }
          heartBeatPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public Builder clearHeartBeatPacket() {
        if (heartBeatPacketBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartBeatPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeatPacket.Builder getHeartBeatPacketBuilder() {
        return getHeartBeatPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public raft.proto.HeartBeatRPC.HeartBeatPacketOrBuilder getHeartBeatPacketOrBuilder() {
        if ((payloadCase_ == 3) && (heartBeatPacketBuilder_ != null)) {
          return heartBeatPacketBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (raft.proto.HeartBeatRPC.HeartBeatPacket) payload_;
          }
          return raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.HeartBeatRPC.HeartBeatPacket, raft.proto.HeartBeatRPC.HeartBeatPacket.Builder, raft.proto.HeartBeatRPC.HeartBeatPacketOrBuilder> 
          getHeartBeatPacketFieldBuilder() {
        if (heartBeatPacketBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = raft.proto.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
          }
          heartBeatPacketBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              raft.proto.HeartBeatRPC.HeartBeatPacket, raft.proto.HeartBeatRPC.HeartBeatPacket.Builder, raft.proto.HeartBeatRPC.HeartBeatPacketOrBuilder>(
                  (raft.proto.HeartBeatRPC.HeartBeatPacket) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        return heartBeatPacketBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.VoteRPC.VoteRPCPacket, raft.proto.VoteRPC.VoteRPCPacket.Builder, raft.proto.VoteRPC.VoteRPCPacketOrBuilder> voteRPCPacketBuilder_;
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public boolean hasVoteRPCPacket() {
        return payloadCase_ == 4;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public raft.proto.VoteRPC.VoteRPCPacket getVoteRPCPacket() {
        if (voteRPCPacketBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (raft.proto.VoteRPC.VoteRPCPacket) payload_;
          }
          return raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return voteRPCPacketBuilder_.getMessage();
          }
          return raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public Builder setVoteRPCPacket(raft.proto.VoteRPC.VoteRPCPacket value) {
        if (voteRPCPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          voteRPCPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public Builder setVoteRPCPacket(
          raft.proto.VoteRPC.VoteRPCPacket.Builder builderForValue) {
        if (voteRPCPacketBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          voteRPCPacketBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public Builder mergeVoteRPCPacket(raft.proto.VoteRPC.VoteRPCPacket value) {
        if (voteRPCPacketBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance()) {
            payload_ = raft.proto.VoteRPC.VoteRPCPacket.newBuilder((raft.proto.VoteRPC.VoteRPCPacket) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            voteRPCPacketBuilder_.mergeFrom(value);
          }
          voteRPCPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public Builder clearVoteRPCPacket() {
        if (voteRPCPacketBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          voteRPCPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public raft.proto.VoteRPC.VoteRPCPacket.Builder getVoteRPCPacketBuilder() {
        return getVoteRPCPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public raft.proto.VoteRPC.VoteRPCPacketOrBuilder getVoteRPCPacketOrBuilder() {
        if ((payloadCase_ == 4) && (voteRPCPacketBuilder_ != null)) {
          return voteRPCPacketBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (raft.proto.VoteRPC.VoteRPCPacket) payload_;
          }
          return raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.VoteRPC.VoteRPCPacket, raft.proto.VoteRPC.VoteRPCPacket.Builder, raft.proto.VoteRPC.VoteRPCPacketOrBuilder> 
          getVoteRPCPacketFieldBuilder() {
        if (voteRPCPacketBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = raft.proto.VoteRPC.VoteRPCPacket.getDefaultInstance();
          }
          voteRPCPacketBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              raft.proto.VoteRPC.VoteRPCPacket, raft.proto.VoteRPC.VoteRPCPacket.Builder, raft.proto.VoteRPC.VoteRPCPacketOrBuilder>(
                  (raft.proto.VoteRPC.VoteRPCPacket) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        return voteRPCPacketBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.Ping.PingMessage, raft.proto.Ping.PingMessage.Builder, raft.proto.Ping.PingMessageOrBuilder> trivialPingBuilder_;
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public boolean hasTrivialPing() {
        return payloadCase_ == 5;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public raft.proto.Ping.PingMessage getTrivialPing() {
        if (trivialPingBuilder_ == null) {
          if (payloadCase_ == 5) {
            return (raft.proto.Ping.PingMessage) payload_;
          }
          return raft.proto.Ping.PingMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 5) {
            return trivialPingBuilder_.getMessage();
          }
          return raft.proto.Ping.PingMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public Builder setTrivialPing(raft.proto.Ping.PingMessage value) {
        if (trivialPingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          trivialPingBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public Builder setTrivialPing(
          raft.proto.Ping.PingMessage.Builder builderForValue) {
        if (trivialPingBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          trivialPingBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public Builder mergeTrivialPing(raft.proto.Ping.PingMessage value) {
        if (trivialPingBuilder_ == null) {
          if (payloadCase_ == 5 &&
              payload_ != raft.proto.Ping.PingMessage.getDefaultInstance()) {
            payload_ = raft.proto.Ping.PingMessage.newBuilder((raft.proto.Ping.PingMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 5) {
            trivialPingBuilder_.mergeFrom(value);
          }
          trivialPingBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public Builder clearTrivialPing() {
        if (trivialPingBuilder_ == null) {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
          }
          trivialPingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public raft.proto.Ping.PingMessage.Builder getTrivialPingBuilder() {
        return getTrivialPingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public raft.proto.Ping.PingMessageOrBuilder getTrivialPingOrBuilder() {
        if ((payloadCase_ == 5) && (trivialPingBuilder_ != null)) {
          return trivialPingBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 5) {
            return (raft.proto.Ping.PingMessage) payload_;
          }
          return raft.proto.Ping.PingMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          raft.proto.Ping.PingMessage, raft.proto.Ping.PingMessage.Builder, raft.proto.Ping.PingMessageOrBuilder> 
          getTrivialPingFieldBuilder() {
        if (trivialPingBuilder_ == null) {
          if (!(payloadCase_ == 5)) {
            payload_ = raft.proto.Ping.PingMessage.getDefaultInstance();
          }
          trivialPingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              raft.proto.Ping.PingMessage, raft.proto.Ping.PingMessage.Builder, raft.proto.Ping.PingMessageOrBuilder>(
                  (raft.proto.Ping.PingMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 5;
        return trivialPingBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:WorkMessage)
    }

    static {
      defaultInstance = new WorkMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:WorkMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WorkMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nWork.proto\032\026AppendEntriesRPC.proto\032\022He" +
      "artBeatRPC.proto\032\rVoteRPC.proto\032\nPing.pr" +
      "oto\"\337\001\n\013WorkMessage\022\025\n\runixTimeStamp\030\001 \002" +
      "(\003\0223\n\023appendEntriesPacket\030\002 \001(\0132\024.Append" +
      "EntriesPacketH\000\022+\n\017heartBeatPacket\030\003 \001(\013" +
      "2\020.HeartBeatPacketH\000\022\'\n\rvoteRPCPacket\030\004 " +
      "\001(\0132\016.VoteRPCPacketH\000\022#\n\013trivialPing\030\005 \001" +
      "(\0132\014.PingMessageH\000B\t\n\007payloadB\014\n\nraft.pr" +
      "oto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          raft.proto.AppendEntriesRPC.getDescriptor(),
          raft.proto.HeartBeatRPC.getDescriptor(),
          raft.proto.VoteRPC.getDescriptor(),
          raft.proto.Ping.getDescriptor(),
        }, assigner);
    internal_static_WorkMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WorkMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_WorkMessage_descriptor,
        new java.lang.String[] { "UnixTimeStamp", "AppendEntriesPacket", "HeartBeatPacket", "VoteRPCPacket", "TrivialPing", "Payload", });
    raft.proto.AppendEntriesRPC.getDescriptor();
    raft.proto.HeartBeatRPC.getDescriptor();
    raft.proto.VoteRPC.getDescriptor();
    raft.proto.Ping.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
